const typhoonApiForm = document.querySelector("#typhoonApiForm");
const typhoonApiStatus = document.querySelector("#typhoonApiStatus");
const stormCards = document.querySelector("#stormCards");
const trackTableBody = document.querySelector("#trackTableBody");
const mapUpdated = document.querySelector("#mapUpdated");
const refreshMap = document.querySelector("#refreshMap");
const stormSummary = document.querySelector("#stormSummary");
const timelineList = document.querySelector("#timelineList");
const typhoonListForm = document.querySelector("#typhoonListForm");
const typhoonYear = document.querySelector("#typhoonYear");
const typhoonSelect = document.querySelector("#typhoonSelect");
const typhoonSeq = document.querySelector("#typhoonSeq");
const typhoonListStatus = document.querySelector("#typhoonListStatus");
const typhoonListGrid = document.querySelector("#typhoonListGrid");
const koreaTyphoonForm = document.querySelector("#koreaTyphoonForm");
const koreaYear = document.querySelector("#koreaYear");
const koreaOnlyAffected = document.querySelector("#koreaOnlyAffected");
const koreaTyphoonStatus = document.querySelector("#koreaTyphoonStatus");
const impactSummary = document.querySelector("#impactSummary");
const koreaTyphoonGrid = document.querySelector("#koreaTyphoonGrid");

let typhoonMap, typhoonLayer, labelLayer, autoRefreshId;
let typhoonList = [];
let selectedTyphoon = null;

const koreanLabels = [[37.5665,126.9780,"서울"],[35.1796,129.0756,"부산"],[33.4996,126.5312,"제주"],[34.8118,126.3922,"목포"],[37.4563,126.7052,"인천"],[35.1595,126.8526,"광주"],[36.3504,127.3845,"대전"],[35.8714,128.6014,"대구"],[35.5384,129.3114,"울산"],[34.7604,127.6622,"여수"],[26.2124,127.6809,"오키나와"],[33.5904,130.4017,"후쿠오카"],[35.6762,139.6503,"도쿄"],[31.2304,121.4737,"상하이"],[25.0330,121.5654,"타이베이"],[14.5995,120.9842,"마닐라"],[22.3193,114.1694,"홍콩"],[13.4443,144.7937,"괌"],[30,135,"북서태평양","ocean"],[34.5,128.2,"남해","ocean"],[33.2,124.5,"동중국해","ocean"]];
const sampleList = [{ id:"2012-07", year:2012, sequence:7, status:"종료", effectLabel:"상륙", startTimeUtc:"201207160600", endTimeUtc:"201207190300", nameKo:"카눈", nameEn:"KHANUN", description:"제7호 태풍 카눈은 한반도에 상륙한 태풍입니다." },{ id:"2012-14", year:2012, sequence:14, status:"종료", effectLabel:"상륙", startTimeUtc:"201208190000", endTimeUtc:"201208301500", nameKo:"덴빈", nameEn:"TEMBIN", description:"제14호 태풍 덴빈은 한반도에 영향을 준 태풍입니다." },{ id:"2012-15", year:2012, sequence:15, status:"종료", effectLabel:"직접영향", startTimeUtc:"201208200600", endTimeUtc:"201208282100", nameKo:"볼라벤", nameEn:"BOLAVEN", description:"제15호 태풍 볼라벤은 강한 바람으로 큰 영향을 준 태풍입니다." },{ id:"2012-16", year:2012, sequence:16, status:"종료", effectLabel:"상륙", startTimeUtc:"201209110000", endTimeUtc:"201209180000", nameKo:"산바", nameEn:"SANBA", description:"제16호 태풍 산바는 한반도에 상륙한 태풍입니다." }];
const sampleKoreaTyphoons = [{ year:2016, sequence:16, nameKo:"말라카스", nameEn:"MALAKAS", startDate:"2016-09-13", endDate:"2016-09-20", minPressureHpa:935, maxWindMs:49, effect:2, effectLabel:"직접영향", affectedKorea:true },{ year:2016, sequence:18, nameKo:"차바", nameEn:"CHABA", startDate:"2016-09-28", endDate:"2016-10-06", minPressureHpa:930, maxWindMs:50, effect:1, effectLabel:"상륙", affectedKorea:true }];
const sampleTyphoonData = { ok:true, count:4, storms:[{ id:"2011-09-8", year:2011, typhoonNo:9, sequence:8, latestAnalysis:{ ft:0, forecastTimeUtc:"201107300000", lat:15.7, lon:133.4, direction:"NE", speedKmh:21, pressureHpa:980, maxWindMs:31, radius15Km:300, radius25Km:50, probabilityRadiusKm:null, location:"필리핀 마닐라 동쪽 약 1340 km 부근 해상" }, forecasts:[{ ft:1, forecastHour:24, forecastTimeUtc:"201107310000", lat:17.9, lon:133.1, direction:"N", speedKmh:11, pressureHpa:970, maxWindMs:36, radius15Km:350, radius25Km:null, probabilityRadiusKm:150, location:"필리핀 마닐라 동북동쪽 약 1350 km 부근 해상" },{ ft:1, forecastHour:48, forecastTimeUtc:"201108010000", lat:20.0, lon:133.5, direction:"NNE", speedKmh:10, pressureHpa:960, maxWindMs:40, radius15Km:400, radius25Km:null, probabilityRadiusKm:250, location:"일본 오키나와 남동쪽 약 910 km 부근 해상" },{ ft:1, forecastHour:72, forecastTimeUtc:"201108020000", lat:22.0, lon:133.1, direction:"NNW", speedKmh:10, pressureHpa:950, maxWindMs:43, radius15Km:450, radius25Km:null, probabilityRadiusKm:400, location:"일본 오키나와 남동쪽 약 720 km 부근 해상" }] }] };

function formatValue(value,suffix=""){return value===null||value===undefined||value===""?"-":`${value}${suffix}`;}
function formatUtcTime(value){return !value||value.length!==12?value||"-":`${value.slice(0,4)}-${value.slice(4,6)}-${value.slice(6,8)} ${value.slice(8,10)}:${value.slice(10,12)}`;}
function collectStormPoints(storm){const points=[];if(storm?.latestAnalysis)points.push(storm.latestAnalysis);return points.concat(storm?.forecasts||[]);}
function typhoonId(typhoon){return `${typhoon.year}-${String(typhoon.sequence).padStart(2,"0")}`;}
function initMap(){if(!window.L||typhoonMap)return;typhoonMap=L.map("liveMap",{zoomControl:true,scrollWheelZoom:false,worldCopyJump:true}).setView([31.5,127.8],5);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:9,attribution:"&copy; OpenStreetMap contributors"}).addTo(typhoonMap);typhoonLayer=L.layerGroup().addTo(typhoonMap);labelLayer=L.layerGroup().addTo(typhoonMap);koreanLabels.forEach(([lat,lon,name,type])=>L.marker([lat,lon],{interactive:false,icon:L.divIcon({className:`korean-map-label ${type||""}`,html:name,iconSize:null})}).addTo(labelLayer));}
function popupHtml(point){return `<div class="typhoon-popup"><strong>${point.ft===0?"분석 위치":`예측 +${point.forecastHour||"-"}h`}</strong><br>${formatUtcTime(point.forecastTimeUtc)} UTC<br>${point.location||"위치 정보 없음"}<br>중심기압 ${formatValue(point.pressureHpa," hPa")} · 최대풍속 ${formatValue(point.maxWindMs," m/s")}<br>강풍반경 ${formatValue(point.radius15Km," km")}</div>`;}
function renderMap(points){initMap();if(!typhoonMap||!typhoonLayer)return;typhoonLayer.clearLayers();const valid=points.filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon));if(!valid.length){typhoonMap.setView([31.5,127.8],5);return;}const latLngs=valid.map(p=>[p.lat,p.lon]);L.polyline(latLngs,{color:"#e4763b",weight:4,opacity:.92,dashArray:"10 8"}).addTo(typhoonLayer);valid.forEach((p,i)=>{const current=p.ft===0||i===0;L.circleMarker([p.lat,p.lon],{radius:current?9:6,color:current?"#e64b35":"#0d5c75",weight:3,fillColor:current?"#e4763b":"#fff",fillOpacity:.95,className:current?"analysis-marker":""}).bindPopup(popupHtml(p)).addTo(typhoonLayer);if(p.radius15Km)L.circle([p.lat,p.lon],{radius:p.radius15Km*1000,color:"#0d5c75",weight:1.4,opacity:.45,fillColor:"#0d5c75",fillOpacity:.08}).addTo(typhoonLayer);if(p.probabilityRadiusKm)L.circle([p.lat,p.lon],{radius:p.probabilityRadiusKm*1000,color:"#6b7c93",weight:1,opacity:.38,dashArray:"6 6",fillOpacity:0}).addTo(typhoonLayer);});typhoonMap.fitBounds(L.latLngBounds(latLngs).pad(.38),{maxZoom:5});}
async function readJsonResponse(res){const contentType=res.headers.get("content-type")||"";const text=await res.text();if(!contentType.includes("application/json")){const isHtml=/^\s*</.test(text);throw new Error(isHtml?"API 주소에서 JSON 대신 HTML 오류 페이지를 받았습니다. Cloudflare Pages Functions 배포와 환경변수 설정을 확인하세요.":"API 응답 형식이 JSON이 아닙니다.");}try{return JSON.parse(text);}catch{throw new Error("API 응답을 JSON으로 해석하지 못했습니다.");}}
function renderTyphoonList(list,fallback=false){typhoonList=list;typhoonListStatus.textContent=`${fallback?"API 연결 전 예시 목록입니다.":"기상청 태풍목록을 불러왔습니다."} 총 ${list.length}개`;typhoonSelect.innerHTML='<option value="">태풍을 선택하세요</option>'+list.map(t=>`<option value="${t.id}">${t.year}년 ${t.sequence}호 ${t.nameKo} (${t.nameEn}) · ${t.effectLabel}</option>`).join("");typhoonListGrid.innerHTML=list.map(t=>`<button class="typhoon-list-card" type="button" data-id="${t.id}"><strong>${t.sequence}호 ${t.nameKo}</strong><span>${t.nameEn}</span><span>${t.effectLabel}</span><span>${t.status}</span><p>${formatUtcTime(t.startTimeUtc)} ~ ${formatUtcTime(t.endTimeUtc)}</p><p>${t.description||"설명 없음"}</p></button>`).join("");typhoonListGrid.querySelectorAll(".typhoon-list-card").forEach(btn=>btn.addEventListener("click",()=>selectTyphoon(btn.dataset.id)));}
function selectTyphoon(id){selectedTyphoon=typhoonList.find(t=>t.id===id)||null;if(typhoonSelect)typhoonSelect.value=id;document.querySelectorAll(".typhoon-list-card").forEach(card=>card.classList.toggle("active",card.dataset.id===id));if(selectedTyphoon){const tmInput=document.querySelector("#typhoonTm");if(tmInput)tmInput.value=selectedTyphoon.endTimeUtc||selectedTyphoon.startTimeUtc||"";if(typhoonSeq&&!typhoonSeq.value)typhoonSeq.value="";stormSummary.textContent=`${selectedTyphoon.year}년 ${selectedTyphoon.sequence}호 ${selectedTyphoon.nameKo}(${selectedTyphoon.nameEn}) 선택됨 · 발표번호를 입력하면 상세 예측을 조회합니다.`;loadTyphoonData();}}
async function loadTyphoonList(event){event?.preventDefault();const year=typhoonYear?.value||new Date().getFullYear();typhoonListStatus.textContent="태풍목록을 불러오는 중입니다.";try{const res=await fetch(`/api/typhoon-list?YY=${encodeURIComponent(year)}`,{cache:"no-store",headers:{Accept:"application/json"}});const data=await readJsonResponse(res);if(!res.ok||!data.ok)throw new Error(data.message||"태풍목록 API 호출 실패");renderTyphoonList(data.typhoons);}catch(error){renderTyphoonList(sampleList,true);typhoonListStatus.textContent=`${error.message} 현재는 예시 목록을 표시합니다.`;}}
function renderKoreaTyphoons(data,fallback=false){if(!koreaTyphoonGrid)return;const all=data.typhoons||[];const affected=data.affected||all.filter(t=>t.affectedKorea);const items=koreaOnlyAffected?.checked?affected:all;const year=data.year||koreaYear?.value||"-";koreaTyphoonStatus.textContent=`${fallback?"API 연결 전 예시 자료입니다.":"우리나라 영향 태풍 자료를 불러왔습니다."} 전체 ${all.length}개 · 표시 ${items.length}개`;impactSummary.textContent=`${year}년 국내 영향 태풍 ${affected.length}개 · 상륙, 직접영향, 간접영향 기준으로 분류했습니다.`;koreaTyphoonGrid.innerHTML=items.length?items.map(t=>`<button class="korea-card" type="button" data-seq="${t.sequence}"><span class="impact-badge impact-${t.effect||0}">${t.effectLabel||"영향 없음"}</span><strong>${t.sequence}호 ${t.nameKo||"이름 없음"}</strong><em>${t.nameEn||"-"}</em><p>${t.startDate||"-"} ~ ${t.endDate||"-"}</p><dl><div><dt>최저기압</dt><dd>${formatValue(t.minPressureHpa," hPa")}</dd></div><div><dt>최대풍속</dt><dd>${formatValue(t.maxWindMs," m/s")}</dd></div></dl></button>`).join(""):'<p class="empty-state">조건에 맞는 태풍이 없습니다. 전체 보기를 해제해 다른 태풍까지 확인하세요.</p>';koreaTyphoonGrid.querySelectorAll(".korea-card").forEach(card=>card.addEventListener("click",()=>{const item=all.find(t=>String(t.sequence)===card.dataset.seq);if(!item)return;selectedTyphoon={id:typhoonId(item),year:item.year||Number(year),sequence:item.sequence,nameKo:item.nameKo,nameEn:item.nameEn,effectLabel:item.effectLabel,startTimeUtc:"",endTimeUtc:""};typhoonYear.value=selectedTyphoon.year;typhoonSeq.value="";document.querySelector("#typhoonTm").value="";typhoonSelect.innerHTML=`<option value="${selectedTyphoon.id}" selected>${selectedTyphoon.year}년 ${selectedTyphoon.sequence}호 ${selectedTyphoon.nameKo} (${selectedTyphoon.nameEn}) · ${selectedTyphoon.effectLabel}</option>`;stormSummary.textContent=`${selectedTyphoon.year}년 ${selectedTyphoon.sequence}호 ${selectedTyphoon.nameKo}(${selectedTyphoon.nameEn}) · ${selectedTyphoon.effectLabel}. 발표번호를 입력하면 태풍정보+예측 API로 상세 경로를 조회합니다.`;location.hash="live";}));}
async function loadKoreaTyphoons(event){event?.preventDefault();const year=koreaYear?.value||new Date().getFullYear();koreaTyphoonStatus.textContent="우리나라 영향 태풍 자료를 불러오는 중입니다.";try{const res=await fetch(`/api/korea-typhoons?year=${encodeURIComponent(year)}&numOfRows=100`,{cache:"no-store",headers:{Accept:"application/json"}});const data=await readJsonResponse(res);if(!res.ok||!data.ok)throw new Error(data.message||"국내 영향 태풍 API 호출 실패");renderKoreaTyphoons(data);}catch(error){renderKoreaTyphoons({year:2016,typhoons:sampleKoreaTyphoons,affected:sampleKoreaTyphoons},true);koreaTyphoonStatus.textContent=`${error.message} 현재는 예시 자료를 표시합니다.`;}}
function renderTyphoonData(data,isFallback=false){const storm=data.storms?.[0];const points=collectStormPoints(storm);const latest=storm?.latestAnalysis||{};const nowText=new Date().toLocaleString("ko-KR",{hour12:false});typhoonApiStatus.textContent=`${isFallback?"API 연결 전 예시 자료를 표시 중입니다.":"기상청 API 자료를 불러왔습니다."} 자료 수: ${data.count||points.length}건`;if(mapUpdated)mapUpdated.textContent=`마지막 갱신: ${nowText}${isFallback?" · 예시":""}`;if(!storm){stormCards.innerHTML="";trackTableBody.innerHTML='<tr><td colspan="6">표시할 태풍 자료가 없습니다.</td></tr>';timelineList.innerHTML="";stormSummary.textContent="표시할 태풍 자료가 없습니다.";renderMap([]);return;}const selectedText=selectedTyphoon?`${selectedTyphoon.nameKo}(${selectedTyphoon.nameEn}) · `:"";stormSummary.textContent=`${selectedText}${storm.year}년 ${storm.typhoonNo}호${storm.sequence?` ${storm.sequence}번 발표`:""} 기준, ${latest.location||"위치 정보 없음"}, 중심기압 ${formatValue(latest.pressureHpa," hPa")}, 최대풍속 ${formatValue(latest.maxWindMs," m/s")}, 이동 ${formatValue(latest.direction)} ${formatValue(latest.speedKmh," km/h")}입니다.`;stormCards.innerHTML=`<article><span>태풍번호</span><strong>${storm.year}-${String(storm.typhoonNo).padStart(2,"0")}</strong><p>${storm.sequence?`${storm.sequence}번 발표`:selectedTyphoon?`${selectedTyphoon.nameKo} / ${selectedTyphoon.nameEn}`:latest.location||"위치 정보 없음"}</p></article><article><span>중심기압</span><strong>${formatValue(latest.pressureHpa," hPa")}</strong><p>낮을수록 강한 태풍입니다.</p></article><article><span>최대풍속</span><strong>${formatValue(latest.maxWindMs," m/s")}</strong><p>강풍 피해 판단 핵심 지표입니다.</p></article><article><span>이동</span><strong>${formatValue(latest.direction)} · ${formatValue(latest.speedKmh," km/h")}</strong><p>방향과 속도 변화를 확인하세요.</p></article>`;timelineList.innerHTML=points.map(p=>`<div class="timeline-item"><strong>${p.ft===0?"현재 분석":`+${p.forecastHour||"-"}시간`}</strong><span>${formatUtcTime(p.forecastTimeUtc)} UTC</span><span>${formatValue(p.pressureHpa," hPa")} · ${formatValue(p.maxWindMs," m/s")}</span></div>`).join("");trackTableBody.innerHTML=points.map(p=>`<tr><td>${p.ft===0?"분석":`예측 +${p.forecastHour||"-"}h`}</td><td>${formatUtcTime(p.forecastTimeUtc)}</td><td>${p.location||`${formatValue(p.lat)} / ${formatValue(p.lon)}`}</td><td>${formatValue(p.pressureHpa," hPa")}</td><td>${formatValue(p.maxWindMs," m/s")}</td><td>강풍 ${formatValue(p.radius15Km," km")} · 확률 ${formatValue(p.probabilityRadiusKm," km")}</td></tr>`).join("");renderMap(points);}
async function loadTyphoonData(event,options={}){event?.preventDefault();const tm=document.querySelector("#typhoonTm")?.value.trim()||"";const seq=typhoonSeq?.value.trim();typhoonApiStatus.textContent=options.silent?"자동 갱신 중입니다.":"기상청 API 자료를 불러오는 중입니다.";try{const query=new URLSearchParams();query.set("mode","1");let endpoint="/api/typhoon";if(selectedTyphoon&&seq){endpoint="/api/typhoon-detail";query.set("YY",selectedTyphoon.year);query.set("typ",selectedTyphoon.sequence);query.set("seq",seq);}else{if(tm)query.set("tm",tm);if(selectedTyphoon)query.set("typ",selectedTyphoon.sequence);}const res=await fetch(`${endpoint}?${query.toString()}`,{cache:"no-store",headers:{Accept:"application/json"}});const data=await readJsonResponse(res);if(!res.ok||!data.ok)throw new Error(data.message||"API 호출에 실패했습니다.");renderTyphoonData(data);}catch(error){renderTyphoonData(sampleTyphoonData,true);typhoonApiStatus.textContent=`${error.message} 현재는 예시 자료로 지도 구성을 보여줍니다.`;}}

initMap();
typhoonListForm.addEventListener("submit",loadTyphoonList);
typhoonSelect.addEventListener("change",()=>selectTyphoon(typhoonSelect.value));
typhoonApiForm.addEventListener("submit",loadTyphoonData);
refreshMap?.addEventListener("click",()=>loadTyphoonData());
koreaTyphoonForm?.addEventListener("submit",loadKoreaTyphoons);
koreaOnlyAffected?.addEventListener("change",()=>loadKoreaTyphoons());
renderTyphoonList(sampleList,true);
renderKoreaTyphoons({year:2016,typhoons:sampleKoreaTyphoons,affected:sampleKoreaTyphoons},true);
renderTyphoonData(sampleTyphoonData,true);
autoRefreshId=window.setInterval(()=>loadTyphoonData(null,{silent:true}),10*60*1000);
window.addEventListener("beforeunload",()=>window.clearInterval(autoRefreshId));
